"""add buyer email

Revision ID: 2aea7db83d82
Revises: f81f90abfb26
Create Date: 2023-12-01 13:26:35.452236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aea7db83d82'
down_revision: Union[str, None] = 'f81f90abfb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyer_email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'buyer_email')
    # ### end Alembic commands ###
