"""account models

Revision ID: 4899a7d9d376
Revises: 7cb60b628a04
Create Date: 2023-11-26 23:18:20.157292

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4899a7d9d376'
down_revision: Union[str, None] = '7cb60b628a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_tbl = op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=320), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('normalized_user_name', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('street', sa.String(length=400), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    with open("alembic/data/customer.json") as json_file:
        json_data = json.load(json_file)
        op.bulk_insert(user_tbl, json_data)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_addresses')
    op.drop_table('users')
    # ### end Alembic commands ###
