"""update models

Revision ID: 767508af630e
Revises: 7cb60b628a04
Create Date: 2023-12-02 21:56:58.929171

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767508af630e'
down_revision: Union[str, None] = '7cb60b628a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    delivery_methods_tbl = op.create_table('delivery_methods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('delivery_time', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    order_statuses_tbl = op.create_table('order_statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    user_tbl = op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=320), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('normalized_user_name', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_email', sa.String(), nullable=False),
    sa.Column('payment_type', sa.Enum('CASH', 'CREDIT_CARD', 'DEBIT_CARD', name='paymenttype'), nullable=False),
    sa.Column('delivery_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('billing_address_id', sa.BigInteger(), nullable=False),
    sa.Column('shipping_address_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_method_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['billing_address_id'], ['billing_addresses.id'], ),
    sa.ForeignKeyConstraint(['delivery_method_id'], ['delivery_methods.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['shipping_addresses.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['order_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    addresses_tbl = op.create_table('user_addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('street', sa.String(length=400), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    with open("alembic/data/customer.json") as json_file:
        json_data = json.load(json_file)
        op.bulk_insert(user_tbl, json_data)

    with open("alembic/data/delivery.json") as json_file:
        json_data = json.load(json_file)
        op.bulk_insert(delivery_methods_tbl, json_data)

    with open("alembic/data/address.json") as json_file:
        json_data = json.load(json_file)
        op.bulk_insert(addresses_tbl, json_data)

    with open("alembic/data/status.json") as json_file:
        json_data = json.load(json_file)
        op.bulk_insert(order_statuses_tbl, json_data)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('user_addresses')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('shipping_addresses')
    op.drop_table('order_statuses')
    op.drop_table('delivery_methods')
    op.drop_table('billing_addresses')
    # ### end Alembic commands ###
