"""init

Revision ID: 7cb60b628a04
Revises: 
Create Date: 2023-11-16 22:10:47.120904

"""
import json
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cb60b628a04"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    product_brands_tbl = op.create_table(
        "product_brands",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    product_types_tbl = op.create_table(
        "product_types",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    products_tbl = op.create_table(
        "products",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("picture_url", sa.String(), nullable=False),
        sa.Column("product_brand_id", sa.BigInteger(), nullable=False),
        sa.Column("product_type_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_brand_id"],
            ["product_brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with open("alembic/data/brands.json") as json_file:
        json_data = json.load(json_file)
        op.bulk_insert(product_brands_tbl, json_data)

    with open("alembic/data/types.json") as json_file:
        json_data = json.load(json_file)
        op.bulk_insert(product_types_tbl, json_data)

    with open("alembic/data/products.json") as json_file:
        json_data = json.load(json_file)
        op.bulk_insert(products_tbl, json_data)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    op.drop_table("product_types")
    op.drop_table("product_brands")
    # ### end Alembic commands ###
