"""embedded delivery time

Revision ID: ba020090ed3d
Revises: 2aea7db83d82
Create Date: 2023-12-01 13:39:19.987813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba020090ed3d'
down_revision: Union[str, None] = '2aea7db83d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_method_short_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_method_delivery_time', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_method_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_constraint('orders_delivery_method_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_method_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_method_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_delivery_method_id_fkey', 'orders', 'delivery_methods', ['delivery_method_id'], ['id'])
    op.drop_column('orders', 'delivery_method_price')
    op.drop_column('orders', 'delivery_method_delivery_time')
    op.drop_column('orders', 'delivery_method_short_name')
    # ### end Alembic commands ###
