"""update payment method table

Revision ID: f81f90abfb26
Revises: 3bcdde1d8f93
Create Date: 2023-11-30 21:48:35.263104

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f81f90abfb26"
down_revision: Union[str, None] = "3bcdde1d8f93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment_methods", sa.Column("code", sa.String(), nullable=False))
    # ### end Alembic commands ###

    meta = sa.MetaData()

    meta.reflect(bind=op.get_bind())

    payment_methods_tbl = sa.Table("payment_methods", meta)

    with open("alembic/data/payment.json") as json_file:
        json_data = json.load(json_file)
        op.bulk_insert(payment_methods_tbl, json_data)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_methods", "code")
    # ### end Alembic commands ###
